export * from './table-versions.module'
export * from './controllers/recommendation-versions.controller'
export * from './services/recommendation-versions.service'
export * from './pipes/request-body-recommendation-versions'
export * from './models/recommendation-version'
